[package]
name = "compar"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }
encoding_rs = "0.8.35"
indicatif = "0.18.2"
memchr = "2.7.6"
unicode-normalization = "0.1.25"
